### ISSUE TITLE
220_Das_SingleCellRNASeq.Rmd

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/BiocWorkshops#22] opened 2018-07-07 15:25 UTC
I'm creating an issue for each workshop, to be closed when both 1) the workshop is complete, and 2) it compiles without problems. Please note problems and status updates here.

aroma.light issue, to be resolved on server side.

**Comment by HenrikBengtsson** [comment] 2018-07-09 14:46
That:
```r
Error in project_to_curve(X, s, pcurve$ord, stretch = stretch) : 
  unused argument (pcurve$ord)
```
appears to come from princurve.  For troubleshooting purposes, see if it works with https://cran.r-project.org/src/contrib/Archive/princurve/princurve_1.1-12.tar.gz.

BTW, what timeline are you on here?  I can try to push for a CRAN update of princurve - they seem to be willing to make a new release quite soon.

**Comment by LiNk-NY** [comment] 2018-07-09 18:43
Hi Henrik, 
I get a different error: 

```
Quitting from lines 393-397 (220_Das_SingleCellRNASeq.Rmd) 
Error: package 'princurve' 1.1.12 is loaded, but >= 2.0.2 is required by 'slingshot'
Execution halted
```

**Comment by kstreet13** [comment] 2018-07-09 18:49
Hey all,
The `project_to_curve` function was added in princurve version 2.0.2 (it was previously called `get.lam`), so I think updating that package may solve this issue.

**Comment by rcannood** [comment] 2018-07-09 20:49
The problem with `aroma.light` has been fixed with princurve 2.0.4.

**Comment by LiNk-NY** [comment] 2018-07-09 21:24
Thanks!

**Comment by rcannood** [comment] 2018-07-09 21:45
And the problem with `slingshot` is being caused by princurve 2.0.4. kstreet13/slingshot#19 should do the trick.

**Comment by HenrikBengtsson** [comment] 2018-07-09 23:13
I can confirm that **aroma.light** passes `R CMD check --as-cran` with the [princurve 2.0.4](https://cran.r-project.org/package=princurve) that just hit CRAN.  I've/Travis CI/AppVeyor CI verified on Linux and Windows with various R versions - as soon as macOS binaries are rolled out, I'd expect it to also work there too.  This means that aroma.light should build and pass all checks on Bioc release & devel at the next round of Bioc builds.

**Comment by LiNk-NY** [comment] 2018-07-10 16:31
```
Quitting from lines 400-404 (220_Das_SingleCellRNASeq.Rmd) 
Error in project_to_curve(X, s, pcurve$ord, stretch = stretch) : 
  unused argument (pcurve$ord)
Calls: local ... getCurves -> .local -> lapply -> FUN -> .shrink_to_avg
In addition: Warning messages:
1: In rgl.init(initValue, onlyNULL) : RGL: unable to open X11 display
2: 'rgl_init' failed, running with rgl.useNULL = TRUE 
Execution halted
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile 220_Das_SingleCellRNASeq.Rmd
Calls: <Anonymous> ... render_new_session -> tryCatch -> tryCatchList -> Rscript_render
Execution halted

Exited with status 1.
```

**Comment by rcannood** [comment] 2018-07-10 17:04
kstreet/slingshot#19 was merged yesterday, but slingshot v 0.99.11 still needs to be published on Bioconductor. Once slingshot v 0.99.11 is out, this error should disappear :)

**Comment by kstreet13** [comment] 2018-07-10 17:38
Yeah, I pushed the new version yesterday, so it should be available soon!

**Comment by drisso** [comment] 2018-07-17 18:38
Hi @LiNk-NY ,

can you confirm that the new version of slingshot solves the issue above? It works on my local machine with slingshot 0.99.12 and princurve 2.1.0, but not sure which versions you have for the build.

**Comment by LiNk-NY** [comment] 2018-07-17 18:55
Hi Davide, @drisso 
The builder has these versions:
```
> packageVersion("slingshot")
[1] ‘0.99.12’
> packageVersion("princurve")
[1] ‘2.1.0’
```
and it solves the issue. Thanks.

**Comment by drisso** [comment] 2018-07-17 18:56
Awesome! Thanks Marcel!

**Comment by LiNk-NY** [comment] 2018-07-18 16:07
Hi Diya, @diyadas 
Could you please fix the citations in your workshop? I don't see any entries in the `.bib` file for: 
```
pandoc-citeproc: reference Peer2017 not found
pandoc-citeproc: reference Pierson2015 not found
pandoc-citeproc: reference Tseng2005 not found
```

**Comment by diyadas** [comment] 2018-07-18 16:43
Will do! Have small formatting things I will also address. Thanks Marcel!

**Comment by diyadas** [comment] 2018-07-25 13:34
I did fix the citation issue locally - but I'm unable to push commits. Any chance that someone could check the permissions I have? So sorry for the last-minute change.

**Comment by seandavi** [comment] 2018-07-25 14:46
@diyadas, could you make a pull request with just that change? We have disabled commits on the repo for everyone, as the workflows are "live" now. Sorry for the inconvenience.

**Comment by diyadas** [comment] 2018-07-25 15:31
PR submitted, sorry if you got a lot of notifications as I had an interesting time with GitHub.

**Closed** 2018-07-25 15:38 UTC
Labels: looks OK
